/* AUTO-GENERATED by tools/gen_assets.py - DO NOT EDIT.
 * Embedded Dungeon Crawl Stone Soup tiles (CC0). */
#ifndef ASSETS_H
#define ASSETS_H

typedef struct { const unsigned char *png; int len; } EmbeddedPng;

extern const EmbeddedPng ASSET_WALL[];
extern const int        ASSET_WALL_N;
extern const EmbeddedPng ASSET_FLOOR[];
extern const int        ASSET_FLOOR_N;
extern const EmbeddedPng ASSET_CEIL;
extern const EmbeddedPng ASSET_DOOR;
extern const EmbeddedPng ASSET_MOB[];
extern const int        ASSET_MOB_N;
extern const EmbeddedPng ASSET_ITEM[];
extern const int        ASSET_ITEM_N;

#endif /* ASSETS_H */
